image: node:8

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
  only:
    - master

deploy:
  stage: deploy
  image: ruby:2.2
  script:
    - apt-get update -yq
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    # - dpl --provider=heroku --app=<YOUR_HEROKU_APP_NAME> --api-key=<YOUR_HEROKU_API_KEY>
